name: soc_grocery
description: SOC PTIT

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: 5.1.0
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.1
  cupertino_icons: 1.0.2
  get: 4.6.5
  get_cli:
  connectivity_plus: 3.0.3
  bot_toast: 4.0.3
  flutter_svg: 2.0.4
  shared_preferences: 2.0.20
  intl: 0.18.0
  freezed: 2.3.2
  freezed_annotation: 2.2.0
  json_annotation: 4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  retrofit_generator: 6.0.0+1
  build_runner: 2.3.3
  json_serializable: 6.6.1

flutter:

  uses-material-design: true