name: soc_grocery
description: SOC PTIT

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  get: 4.6.5
  get_cli:

  # Network
  dio: 5.1.0
  pretty_dio_logger: 1.3.1
  retrofit: 4.0.1

  # Utils
  connectivity_plus: 3.0.3
  intl: 0.17.0
  geolocator: 9.0.2
  flutter_geocoder: ^0.2.2-nulgeocolsafety

  # Code gen
  freezed_annotation: 2.2.0
  json_annotation: 4.8.0
  freezed: 2.3.2

  #local storage
  shared_preferences: 2.0.20

  # firebase
  google_sign_in: 6.0.2
  firebase_core: 2.9.0
  firebase_auth: 4.4.0
  firebase_analytics: 10.2.0

  # UI
  cupertino_icons: 1.0.2
  bot_toast: 4.0.3
  flutter_svg: 2.0.4
  gap: 2.0.1
  lottie: 2.3.2
  google_fonts: 4.0.3
  sign_in_button: 3.2.0
  carousel_slider: 4.2.1
  cached_network_image: 3.2.3
  flutter_rating_bar: 4.0.1

  momo_vn: 2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 2.0.0
  retrofit_generator: 6.0.0+1
  build_runner: 2.3.3
  json_serializable: 6.6.1
  flutter_gen_runner: 5.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/icons/

flutter_gen:
  output: lib/app/config/